### ISSUE TITLE
mapProgramT

### ISSUE THREAD

**Issue by andrewthad** [HeinrichApfelmus/operational#16]
In PR https://github.com/HeinrichApfelmus/operational/pull/15, I've added a function that makes it possible to map over the instruction type that `ProgramT` is parameterized over.

**Comment by andrewthad** [comment]
From what I learned in https://github.com/HeinrichApfelmus/operational/issues/14, I thought that it would be possible to also write the functions

    mapProgramT :: (forall a. instr1 a -> instr2 a) -> ProgramT instr1 m b -> ProgramT instr2 m b
    hoistProgramT :: (forall b. m b -> n b) -> ProgramT instr m a -> ProgramT instr n b

without pattern matching on `ProgramT`. However, I still cannot find a way to write `mapProgramT` with pattern matching, so I think that this PR is still relevant.

**Comment by HeinrichApfelmus** [comment]
The same ideas from #14 can be used to write `mapProgramT`. Here is one way to do it:

```haskell
mapProgramT :: Monad m => (forall a. instr1 a -> instr2 a)
    -> ProgramT instr1 m b -> ProgramT instr2 m b
mapProgramT f p = do
    v <- lift $ viewT p
    case v of
        Return a -> return a
        i :>>= k -> singleton (f i) >>= mapProgramT f . k
```

----

If I were to export the constructors, then this would kind of the defeat the purpose of the library. (Though I'm willing to compromise for the sake of efficiency). Relying on `viewT` only makes sure that the monad laws and the lifting laws are always satisfied. In contrast, having access to the internal constructors risks breaking these laws.
