### ISSUE TITLE
ProgramT and ProgramViewT are not really GADTs

### ISSUE THREAD

**Issue by bfrk** [HeinrichApfelmus/operational#18]
As recently pointed out by Oleg Kiselyov and Hiromi Ishii (http://okmij.org/ftp/Haskell/extensible/more.pdf) your GADTs are not actually GADTs but rather (only) existentially quantified data types in GADT notation. Your comments about certain example functions requiring type signatures are therefore wrong: these signatures are not needed (I verified this with ghc-7.10.3). The comments and examples in the code should be fixed accordingly.

**Comment by HeinrichApfelmus** [comment]
Thanks for pointing this out! I have changed the language extensions used and the remarks in the documentation, but I am leaving the example code as is, as type signatures are useful for documentation purposes.
