### ISSUE TITLE
Issues with `.cabal` file

### ISSUE THREAD

**Issue by hvr** [HeinrichApfelmus/operational#20]
The .cabal file contains

```
Executable operational-TicTacToe
    if flag(buildExamples)
        build-depends:  random == 1.*
        cpp-options: -DbuildExamples
    else
        buildable: False
    main-is:            doc/examples/TicTacToe.hs
    hs-source-dirs:     src, .
    other-modules:      Control.Monad.Operational
```

However, this fails to compile (with more recent cabals) since the dependency on `mtl` and `base` are missing (they are *not* inherited from the `library`'s section).

Also it seems strange that the `library` section declares `extensions`, which the executable doesn't, even though it compiles `Control.Monad.Operational` directly. Also, `cpp-options: -DbuildExamples` seems to have no purpose, as there doesn't appear to be any CPP conditional being affected by that. Also there's a modern idiom for building executables which use the package's library by simply build-depending on the package...

EDIT: long story short, I made a PR (#21) to demonstrate what I mean :-)

EDIT2: Turns out this is actually a bug in cabal's legacy cabal spec version support (https://github.com/haskell/cabal/issues/4121) - but it may make sense to update the .cabal file nevertheless

**Comment by HeinrichApfelmus** [comment]
Thanks! I have merged the pull request and uploaded a new version to hackage. I hope this resolves the issue?

**Comment by hvr** [comment]
@HeinrichApfelmus looks good to me! Thanks
